title: Yoon Hee Seung
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "HeeSeungYoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Yoon Hee Seung # add your name
author-img: yoon-hee-seung.jpg
about-author: I am an AI developer. Always hungry to keep learning. # add description
social-github: HeeSeungYoon/Portfolio # add your Github handle
social-linkedin: heeseung-yoon-b0994510a
social-email: iyhs1858@gmail.com # add your Email address

# Disqus
discus-identifier: 
  comments : false # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-toc

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

toc: true